spring:
  profiles:
    default: test
  application:
    name: up-data
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  elasticsearch:
    uris: 101.79.11.20:9200
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}

logging:
  level:
    root: info
    com.sh.updown: debug

server:
  servlet:
    context-path: /app

app:
  version: 0.0.1