# 사용자 정의 속성
profile:
  value: 'test'
spring:
  datasource:
    url: ${TEST_DB_URL}
    username: ${TEST_DB_USERNAME}
    password: ${TEST_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  batch:
    job:
      enabled: true
#    jdbc:
#      initialize-schema: always

logging:
    level:
      root: info
      com.sh.updown: debug

server:
    servlet:
      context-path: /app

